#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025 IObundle
#
# SPDX-License-Identifier: MIT
"""Merge CVA6 SystemVerilog sources into a single flat file.

The OpenHWGroup CVA6 RTL is a tree of interdependent SystemVerilog
packages and modules.  Downstream tools (Vivado, Quartus, simulators)
read sources in the order given on their command line / file list.  A
flat glob (e.g. ``$(wildcard ../src/*.sv)``) orders files alphabetically,
which can place a *module* before the *package* it references in its
port/parameter list -- the root cause of errors like
``[Synth 8-1031] ariane_pkg is not declared``.

This script concatenates every source into ONE file in dependency
order: first all packages (topologically sorted), then all modules.
It also inlines every `` `include "x.svh" `` at its exact site, so the
output is a single self-contained file with no external include
dependency.

Usage:
    cva6_merge.py OUT.sv PKG1.sv PKG2.sv ... MOD1.sv MOD2.sv ...

Banner comments between concatenated files record the original
basename for later traceback / debugging.
"""

import os
import re
import sys

INCLUDE_RE = re.compile(r'^(\s*)`include\s+"([^"]+)"\s*$')

# Header search paths (cannot be inferred from the source files alone,
# because headers like ex_trace_item.svh live in utility dirs that also
# hold no sources). Populated by the Makefile via the CVA6_INCLUDE_DIRS
# environment variable ("path:path:...").
SEARCH_DIRS = os.environ.get('CVA6_INCLUDE_DIRS', '').split(':')
SEARCH_DIRS = [d for d in SEARCH_DIRS if d]


def read_header_includes(svh_names):
    """Map each .svh basename to its full contents (verbatim)."""
    if not SEARCH_DIRS:
        raise SystemExit("ERROR: CVA6_INCLUDE_DIRS not set")
    cache = {}
    for name in svh_names:
        hit = None
        for d in SEARCH_DIRS:
            p = os.path.join(d, name)
            if os.path.isfile(p):
                hit = p
                break
        if hit is None:
            raise SystemExit(
                f"ERROR: header '{name}' not found under {SEARCH_DIRS}")
        with open(hit) as f:
            cache[name] = f.read()
    return cache


def emit(path, out, headers):
    """Emit one source file, inlining `` `include "*.svh" `` lines."""
    base = os.path.basename(path)
    out.write(f"\n// =====================\n")
    out.write(f"// FILE: {base}\n")
    out.write(f"// =====================\n")
    with open(path) as f:
        for lineno, line in enumerate(f, 1):
            m = INCLUDE_RE.match(line)
            if m and m.group(2) in headers:
                indent = m.group(1)
                body = headers[m.group(2)]
                out.write(f"{indent}// `include \"{m.group(2)}\" (inlined from {base}:{lineno})\n")
                for hline in body.splitlines(keepends=True):
                    out.write(indent + hline)
                if not body.endswith('\n'):
                    out.write('\n')
                continue
            out.write(line)


def main(argv):
    if len(argv) < 3:
        raise SystemExit(__doc__)
    out_path = argv[1]
    sources = argv[2:]

    headers = read_header_includes([
        'cvxif_types.svh',
        'rvfi_types.svh',
        'ex_trace_item.svh',
        'instr_trace_item.svh',
        'hpdcache_typedef.svh',
    ])

    with open(out_path, 'w') as out:
        out.write("// cva6.sv - single-file CVA6 (rv32imac + Sv32 MMU +\n")
        out.write("// HPDCACHE_WT, 32-bit AXI4) for IOb-SoC integration.\n")
        out.write("//\n")
        out.write("// AUTO-GENERATED by hardware/cva6_merge.py from the\n")
        out.write("// OpenHWGroup CVA6 submodule + hardware/sv/. Do not edit\n")
        out.write("// by hand. All packages precede all modules; .svh headers\n")
        out.write("// are inlined at their `include sites.\n")
        out.write("// (c) IObundle 2025 - SPDX-License-Identifier: MIT\n")
        out.write("//\n")
        out.write("// HPDCACHE_ASSERT_OFF: the upstream HPDcache wraps its\n")
        out.write("// elaboration-time $fatal checks and runtime SVA assertions\n")
        out.write("// (e.g. the round-robin arbiter gnt_q one-hot check in\n")
        out.write("// hwpf_stride_req_arbiter_i) in `ifndef HPDCACHE_ASSERT_OFF.\n")
        out.write("// For SoC-level integration simulation the testbench\n")
        out.write("// typically does not drive the HWPFO ports, which lets X\n")
        out.write("// propagate into the arbiter's req_i and trips the\n")
        out.write("// assertion. The upstream-blessed escape hatch is to define\n")
        out.write("// this macro. Synthesis ignores `define directives and SVA\n")
        out.write("// property asserts, so this has no effect on Vivado /\n")
        out.write("// Quartus. To re-enable HPDcache assertions (e.g. for\n")
        out.write("// hpdcache unit testing), compile with the override\n")
        out.write("// -uHPDCACHE_ASSERT_OFF on the verilator / vlog command line.\n")
        out.write("`define HPDCACHE_ASSERT_OFF\n")
        out.write("//\n")
        out.write("// The body is wrapped in a Verilator lint_off block for three\n")
        out.write("// warning classes that fire on dead code in our config:\n")
        out.write("//   SELRANGE     - slice widths on PPN/GPPN/VPN inside\n")
        out.write("//                  if (CVA6Cfg.RVH/IS_XLEN64/SvnapotEn) blocks\n")
        out.write("//                  that the synthesizer prunes.\n")
        out.write("//   WIDTHCONCAT  - unsized numbers in the frontend fetch\n")
        out.write("//                  address concatenation (gated by the same\n")
        out.write("//                  config flags).\n")
        out.write("//   SYMRSVDWORD  - struct field named 'register' in\n")
        out.write("//                  cvxif_types.svh's X_REGISTER_T macro.\n")
        out.write("// Vivado and Quartus ignore these pragmas (they are\n")
        out.write("// /* verilator ... */ comments).\n")
        out.write("/*verilator lint_off SELRANGE*/\n")
        out.write("/*verilator lint_off WIDTHCONCAT*/\n")
        out.write("/*verilator lint_off SYMRSVDWORD*/\n")
        for s in sources:
            emit(s, out, headers)
        out.write("/*verilator lint_on SELRANGE*/\n")
        out.write("/*verilator lint_on WIDTHCONCAT*/\n")
        out.write("/*verilator lint_on SYMRSVDWORD*/\n")

    print(f"Wrote {out_path} "
          f"({os.path.getsize(out_path)} bytes, "
          f"{sum(1 for _ in open(out_path))} lines) from {len(sources)} files")


if __name__ == '__main__':
    main(sys.argv)
